### ISSUE TITLE
一些簡化和修正

### ISSUE THREAD

**Issue by jayx1011** [LeonPJ/tw-gas-monitor-demo#1]
1. case '及時油價'： (Line 71)
case '即時油價' // 字打對才專業 XD
2. 程式碼簡化建議 (Line 44 到 62)：
var updown = $('.main h2')[0].className; // 從網站來看，長跟降都有 class, 不調整則無
var sendSticker = (updown === 'up', 123, (updwon === 'down', 120, 122)); // IIF 不知道在這是否能用，不能的話還是有其他寫法的
event.reply({
  type: 'sticker',
  packageId: '1',
  stickerId: sendSticker
});

**Comment by Willis0826** [comment]
@pk9058 
非常好的觀點，在減少 jQuery 重複工作上。
不太確定你指的 [IIF](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator) 是否與我想的一致，如果是，我想正確的格式應該為 : 
`let sendSticker = (updown === 'up' ? 123 : (updown === 'down' ? 120 : 122));`

I hope this helps you.

**Comment by jayx1011** [comment]
@Willis0826 是的沒錯，就是這樣，太久沒摸程式碼，腦袋都打結了 :(

**Comment by LeonPJ** [comment]
感謝兩位寶貴的意見，我會盡快修正
